### ISSUE TITLE
pDNS scripts not working...

### ISSUE THREAD

**Issue by b0rman** [Rikbruggink/Zabbix-templates#1]
Hi!

pDNS scripts not working because of permissions: 

> sudo -u zabbix /etc/init.d/pdns dump
> not running
> 
> sudo -u zabbix /usr/bin/pdns_control list
> Fatal error: Unable to connect to remote '/var/run/pdns.controlsocket': Permission denied

Any ideas?

CentOS 6.3

**Comment by wschoot** [comment]
On 6/13/2013 2:20, b0rman wrote:

> Hi!
> 
> pDNS scripts not working because of permissions:
> 
> ```
> sudo -u zabbix /etc/init.d/pdns dump
> not running
> 
> sudo -u zabbix /usr/bin/pdns_control list
> Fatal error: Unable to connect to remote
> '/var/run/pdns.controlsocket': Permission denied
> ```
> 
> Any ideas?

Two possibilities;

a) powerdns doesn't run
b) the sudo-rules are not applied

Do these commands you show work when run as root without sudo?

Wouter

**Comment by b0rman** [comment]
Hi!

pDNS is up and running.
Commands as root will work and will return actual information - everything is OK, but running commands as zabbix doesn't work (I wrote it before)

**Comment by wschoot** [comment]
I guess the sudo-setup is not right then, just adapt it to your needs.

**Comment by b0rman** [comment]
Do you have any kind of setup for this needs? I mean for sudoers

**Comment by Rikbruggink** [comment]
Instead of sudoers you could add the user zabbix to the pdns group. Sudo is a better solution though.

Rik.
