### ISSUE TITLE
Monitor Storage Device Latency

### ISSUE THREAD

**Issue by alexandrespbr** [Rikbruggink/Zabbix-templates#2]
Hi, 

First of all, congratulations for your template, I'm using it and it´s very helpfull.

Do you have any plan to monitor Storage Device Latency (DAVG) ?

Thanks.

Alexandre

**Comment by Rikbruggink** [comment]
hei Alexandre,

No im not updating my current templates until 2.2 is here., You can always fork my repo, adjust the template to your needs and submit al pull request.

With kind regards,

Rik Bruggink.

-----Oorspronkelijk bericht-----
Afzender: Alexandre notifications@github.com
Verstuurd: Maandag 5 Augustus 2013 17:18
Aan: Rikbruggink/Zabbix-templates Zabbix-templates@noreply.github.com
Onderwerp: [Zabbix-templates] Monitor Storage Device Latency (#2)

Hi, 

First of all, congratulations for your template, I'm using it and it´s very helpfull.

Do you have any plan to monitor Storage Device Latency (DAVG) ?

Thanks.

Alexandre
