### ISSUE TITLE
Zabbix monitoring for Office 365

### ISSUE THREAD

**Issue by jashankochar** [Rikbruggink/Zabbix-templates#4]
Can you please tell how should i monitor office 365 through zabbix. i have seen template of yours for office 365 but want to know about connectivity for monitoring, Thanks for any help.

**Comment by Rikbruggink** [comment]
The template that is in the 2.0 directory is intended to be used to monitor an Office365 directory synchronization service. I believe it is now called Azure AD Dirsync. The templates in my repository are old and probably outdated at this time. You are always welcome to fork but for now i wont be updating any templates.
